import {Links,Meta,Scripts,ScrollRestoration} from "react-router"
import reflexGlobalStyles from "$/styles/__reflex_global_styles.css?url"
import {jsx} from "@emotion/react"
import {Fragment,useEffect} from "react"

export function Layout({children}) {
  return (
    jsx("html",{lang:"pt-BR",suppressHydrationWarning:true},jsx("head",{},jsx("script",{},"\n// Only run in browser environment, not during SSR\nif (typeof document !== 'undefined') {\n    try {\n        const theme = localStorage.getItem(\"theme\") || 'system';\n        const systemPreference = window.matchMedia(\"(prefers-color-scheme: dark)\").matches ? \"dark\" : \"light\";\n        const resolvedTheme = theme === \"system\" ? systemPreference : theme;\n\n        // Apply theme immediately - blocks until complete\n        // Use classList to avoid overwriting other classes\n        document.documentElement.classList.remove(\"light\", \"dark\");\n        document.documentElement.classList.add(resolvedTheme);\n        document.documentElement.style.colorScheme = resolvedTheme;\n\n    } catch (e) {\n        // Fallback to system preference on any error (resolve \"system\" to actual theme)\n        const fallbackTheme = window.matchMedia(\"(prefers-color-scheme: dark)\").matches ? \"dark\" : \"light\";\n        document.documentElement.classList.remove(\"light\", \"dark\");\n        document.documentElement.classList.add(fallbackTheme);\n        document.documentElement.style.colorScheme = fallbackTheme;\n    }\n}\n"),jsx("link",{href:"/codeboxd.css",rel:"stylesheet"},),jsx("link",{href:"https://fonts.googleapis.com",rel:"preconnect"},),jsx("link",{crossOrigin:"",href:"https://fonts.gstatic.com",rel:"preconnect"},),jsx("link",{href:"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap",rel:"stylesheet"},),jsx("style",{suppressHydrationWarning:true},"\nbody {\n  background-color: #000000;\n  color: #ffffff;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n.form-input-custom {\n  background-color: #060606;\n  border: 1px solid #1e1e1e;\n  transition: border-color 0.2s ease, box-shadow 0.2s ease;\n}\n.form-input-custom:focus {\n  outline: none;\n  border-color: #F5B300;\n  box-shadow: 0 0 0 1px #F5B300;\n}\n.custom-checkbox {\n  appearance: none;\n  -webkit-appearance: none;\n  background-color: transparent;\n  border: 1.5px solid #666666;\n  border-radius: 4px;\n  width: 15px;\n  height: 15px;\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  cursor: pointer;\n  position: relative;\n}\n.custom-checkbox:checked {\n  background-color: transparent;\n  border-color: #d1d5db;\n}\n.custom-checkbox:checked::after {\n  content: '';\n  display: block;\n  width: 4px;\n  height: 8px;\n  border: solid #ffffff;\n  border-width: 0 2px 2px 0;\n  transform: rotate(45deg);\n  margin-bottom: 2px;\n}\n"),jsx("meta",{charSet:"utf-8"},),jsx("meta",{content:"width=device-width, initial-scale=1",name:"viewport"},),jsx(Meta,{},),jsx("link",{as:"style",href:reflexGlobalStyles,rel:"preload"},),jsx("link",{href:reflexGlobalStyles,rel:"stylesheet",type:"text/css"},),jsx(Links,{},)),jsx("body",{},children,jsx(ScrollRestoration,{},),jsx(Scripts,{},)))
  )
}