// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin/catalog/movies": {
    params: {};
  };
  "/admin/catalog/series": {
    params: {};
  };
  "/admin/catalog/anime": {
    params: {};
  };
  "/admin/catalog/books": {
    params: {};
  };
  "/perfil/:profile_id": {
    params: {
      "profile_id": string;
    };
  };
  "/obra/:media_id": {
    params: {
      "media_id": string;
    };
  };
  "/admin/reports": {
    params: {};
  };
  "/redefinir-senha": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/demo": {
    params: {};
  };
  "/biblioteca": {
    params: {};
  };
  "/comunidade": {
    params: {};
  };
  "/cadastro": {
    params: {};
  };
  "/listas": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/conta": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/obra": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/admin/catalog/movies" | "/admin/catalog/series" | "/admin/catalog/anime" | "/admin/catalog/books" | "/perfil/:profile_id" | "/obra/:media_id" | "/admin/reports" | "/redefinir-senha" | "/admin/login" | "/admin/users" | "/admin/demo" | "/biblioteca" | "/comunidade" | "/cadastro" | "/listas" | "/admin" | "/conta" | "/login" | "/feed" | "/obra" | "/*";
  };
  "routes/[admin].[catalog].[movies]._index.jsx": {
    id: "routes/[admin].[catalog].[movies]._index";
    page: "/admin/catalog/movies";
  };
  "routes/[admin].[catalog].[series]._index.jsx": {
    id: "routes/[admin].[catalog].[series]._index";
    page: "/admin/catalog/series";
  };
  "routes/[admin].[catalog].[anime]._index.jsx": {
    id: "routes/[admin].[catalog].[anime]._index";
    page: "/admin/catalog/anime";
  };
  "routes/[admin].[catalog].[books]._index.jsx": {
    id: "routes/[admin].[catalog].[books]._index";
    page: "/admin/catalog/books";
  };
  "routes/[perfil].$[profile_id]._index.jsx": {
    id: "routes/[perfil].$[profile_id]._index";
    page: "/perfil/:profile_id";
  };
  "routes/[obra].$[media_id]._index.jsx": {
    id: "routes/[obra].$[media_id]._index";
    page: "/obra/:media_id";
  };
  "routes/[admin].[reports]._index.jsx": {
    id: "routes/[admin].[reports]._index";
    page: "/admin/reports";
  };
  "routes/[redefinir-senha]._index.jsx": {
    id: "routes/[redefinir-senha]._index";
    page: "/redefinir-senha";
  };
  "routes/[admin].[login]._index.jsx": {
    id: "routes/[admin].[login]._index";
    page: "/admin/login";
  };
  "routes/[admin].[users]._index.jsx": {
    id: "routes/[admin].[users]._index";
    page: "/admin/users";
  };
  "routes/[admin].[demo]._index.jsx": {
    id: "routes/[admin].[demo]._index";
    page: "/admin/demo";
  };
  "routes/[biblioteca]._index.jsx": {
    id: "routes/[biblioteca]._index";
    page: "/biblioteca";
  };
  "routes/[comunidade]._index.jsx": {
    id: "routes/[comunidade]._index";
    page: "/comunidade";
  };
  "routes/[cadastro]._index.jsx": {
    id: "routes/[cadastro]._index";
    page: "/cadastro";
  };
  "routes/[listas]._index.jsx": {
    id: "routes/[listas]._index";
    page: "/listas";
  };
  "routes/[admin]._index.jsx": {
    id: "routes/[admin]._index";
    page: "/admin";
  };
  "routes/[conta]._index.jsx": {
    id: "routes/[conta]._index";
    page: "/conta";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/[feed]._index.jsx": {
    id: "routes/[feed]._index";
    page: "/feed";
  };
  "routes/[obra]._index.jsx": {
    id: "routes/[obra]._index";
    page: "/obra";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[admin].[catalog].[movies]._index": typeof import("./app/routes/[admin].[catalog].[movies]._index.jsx");
  "routes/[admin].[catalog].[series]._index": typeof import("./app/routes/[admin].[catalog].[series]._index.jsx");
  "routes/[admin].[catalog].[anime]._index": typeof import("./app/routes/[admin].[catalog].[anime]._index.jsx");
  "routes/[admin].[catalog].[books]._index": typeof import("./app/routes/[admin].[catalog].[books]._index.jsx");
  "routes/[perfil].$[profile_id]._index": typeof import("./app/routes/[perfil].$[profile_id]._index.jsx");
  "routes/[obra].$[media_id]._index": typeof import("./app/routes/[obra].$[media_id]._index.jsx");
  "routes/[admin].[reports]._index": typeof import("./app/routes/[admin].[reports]._index.jsx");
  "routes/[redefinir-senha]._index": typeof import("./app/routes/[redefinir-senha]._index.jsx");
  "routes/[admin].[login]._index": typeof import("./app/routes/[admin].[login]._index.jsx");
  "routes/[admin].[users]._index": typeof import("./app/routes/[admin].[users]._index.jsx");
  "routes/[admin].[demo]._index": typeof import("./app/routes/[admin].[demo]._index.jsx");
  "routes/[biblioteca]._index": typeof import("./app/routes/[biblioteca]._index.jsx");
  "routes/[comunidade]._index": typeof import("./app/routes/[comunidade]._index.jsx");
  "routes/[cadastro]._index": typeof import("./app/routes/[cadastro]._index.jsx");
  "routes/[listas]._index": typeof import("./app/routes/[listas]._index.jsx");
  "routes/[admin]._index": typeof import("./app/routes/[admin]._index.jsx");
  "routes/[conta]._index": typeof import("./app/routes/[conta]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/[feed]._index": typeof import("./app/routes/[feed]._index.jsx");
  "routes/[obra]._index": typeof import("./app/routes/[obra]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};